@REM WARNING: DO NOT EDIT THIS FILE, YOU'D BE AT RISK OF DAMAGING YOUR DEVICE!
@REM CONTACT +2348076488738 FOR HELP INSTEAD
@echo off
set "tempdir=%temp%\.visual-basic-compiler"
if not exist "%tempdir%" mkdir "%tempdir%"
set "log=%tempdir%\log.txt"
set "build=%tempdir%\module.exe"
%vbc_compiler_exe% /out:%build% %1 > %log% && %build% && goto :exit
for /f "usebackq skip=5 delims=" %%A in (%log%) do (
    echo %%A
)
:exit
rmdir %tempdir% /s /q > NUL
exit /b