@REM WARNING: DO NOT EDIT THIS FILE, YOU'D BE AT RISK OF DAMAGING YOUR DEVICE!
@REM CONTACT +2348076488738 FOR HELP INSTEAD
@echo off
if exist "%ProgramFiles(x86)%" (
    set "bit_version=Framework64"
) else set "bit_version=Framework"
set "parent_net=C:\Windows\Microsoft.NET\%bit_version%"
set "regex_pattern=v[0-9]."
set "last_framework_version="
for /f "delims=" %%i in ('dir /b /ad %parent_net% ^| findstr /R "^v[0-9]" ^| sort /r') do (
    set "last_framework_version=%%i"
    goto :done
)
:done
set "compiler=%parent_net%\%last_framework_version%\vbc.exe"
set "tempdir=%temp%\.visual-basic-compiler"
if not exist "%tempdir%" mkdir "%tempdir%"
set "log=%tempdir%\log.txt"
set "build=%tempdir%\module.exe"
%compiler% /out:%build% %1 > %log% && %build% && goto :exit
for /f "usebackq skip=5 delims=" %%A in (%log%) do (
    echo %%A
)
:exit
rmdir %tempdir% /s /q > NUL
exit /b